#!/bin/bash
echo "================================"
echo "Broker SaaS UI Demo 启动脚本"
echo "================================"
echo ""
echo "模块列表："
echo "1. 系统主页 (index.html) - 平台概览和快速导航"
echo "2. 经营总览 (dashboard.html) - 核心业务数据分析"
echo "3. CRM客户中心 (crm.html) - 客户管理和跟进"
echo "4. KYC审核中心 (kyc.html) - 身份审核和风险管理"
echo "5. 钱包与支付中心 (wallet.html) - 资金管理和出金审批"
echo "6. 代理中心 (agent.html) - 代理管理和返佣结算"
echo ""
echo "要启动本地服务器，可以使用以下命令："
echo "python3 -m http.server 8000"
echo "或"
echo "npx serve ."
echo ""
echo "然后在浏览器中访问：http://localhost:8000"
echo "================================"